spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:

    hikari:
      idle-timeout: 60000
      max-lifetime: 1800000
      minimum-idle: 1
      maximum-pool-size: 50
      leak-detection-threshold: 600000
      connection-timeout: 10000




  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: true
    show-sql: true


  liquibase:
    enabled: false
    change-log: classpath:db/changelog/db.changelog-master.yaml
  devtools:
    remote:
      restart:
        enabled: true


redis:
  host: localhost
  port: 6379
  expire_time: ${EXPIRE_TIME:50}
logging:
  level:
    com:
      zaxxer:
        hikari: TRACE


